application: sam-roster
version: 1
runtime: go
api_version: go1

default_expiration: "10m"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- node_modules

handlers:
- url: /
  static_files: ui/app/index.html
  upload: ui/app/index\.html

- url: /fonts
  static_dir: ui/app/fonts/

- url: /styles
  static_dir: ui/app/styles/
  
- url: /images
  static_dir: ui/app/images/

- url: /src
  static_dir: ui/app/src/
  
- url: /bower_components
  static_dir: ui/bower_components/

- url: /.*
  script: _go_app