application: sam-roster
version: 1
runtime: go
api_version: go1

handlers: 
- url: /
  static_files: ui/app/index.html
  upload: ui/app/(.*\.html)

- url: /styles
  static_dir: ui/dist/fonts/

- url: /src
  static_dir: ui/dist/src/

- url: /.*
  script: _go_app
