application: sam-roster
version: 1
runtime: go
api_version: go1

handlers: 
- url: /
  static_files: ui/app/index.html
  upload: ui/app/(.*\.html)

- url: /css
  static_dir: ui/app/css

- url: /.*
  script: _go_app
