application: sam-roster
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: ui/app/index.html
  upload: app/(.*\.html)

- url: /styles
  static_dir: dist/fonts/

- url: /src
  static_dir: dist/src/

- url: /.*
  script: _go_app
