application: sam-roster
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: app/index.html
  upload: app/(.*\.html)

- url: /fonts
  static_dir: app/fonts/

- url: /styles
  static_dir: app/styles/
  
- url: /images
  static_dir: app/images/

- url: /src
  static_dir: app/src/
  
- url: /bower_components
  static_dir: bower_components/

- url: /.*
  script: _go_app